[package]
name = "dreamer"
version = "0.1.0"
authors = ["KernelFreeze <kernelfreeze@outlook.com>"]
edition = "2018"

[workspace]
members = ["crates/youtube-music", "crates/wither", "crates/wither_derive", "crates/rspotify"]

[dependencies]
songbird = { version = "0.1.4", features = ["builtin-queue"] }
dotenv = "0.15.0"
wither = { path = "crates/wither" }
serde = "1.0.123"
futures = "0.3.12"
log = "0.4.14"
simplelog = "0.9.0"
serde_json = "1.0.62"
strfmt = "0.1.6"
youtube-music = { path = "crates/youtube-music" }
regex = "1.4.3"
rspotify = { path = "crates/rspotify" }
flume = "0.10.2"
byteorder = "1.4.2"

[dependencies.serenity]
version = "0.10.2"
features = ["voice", "absolute_ratelimits"]

[dependencies.tokio]
version = "1.2.0"
features = ["macros", "rt-multi-thread"]
