version: '3.7'
services:
  mongo:
    env_file: .env
    image: mongo:latest
    restart: unless-stopped
    environment:
        MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
        MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongodb_data_container:/data/db
  dreamer:
    env_file: .env
    build: .
    environment:
        DATABASE_URI: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongo:27017/dreamer?authSource=admin
        RSPOTIFY_CLIENT_ID: ${RSPOTIFY_CLIENT_ID}
        RSPOTIFY_CLIENT_SECRET: ${RSPOTIFY_CLIENT_SECRET}
        DISCORD_TOKEN: ${DISCORD_TOKEN}
        RUST_LOG: info
        BOT_PREFIX: ${BOT_PREFIX}

volumes:
  mongodb_data_container: